version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt # Install project dependencies
      # - pytest tests/                   # Run unit tests
  post_build:
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_REGION
      - aws ecs update-service --cluster <YOUR_CLUSTER_NAME> --service <YOUR_SERVICE_NAME> --force-new-deployment
artifacts:
  files: "**/*" # This depends on your project structure
